name: rethinkdb
version: 2.2.4
summary: The open-source database for the realtime web
description: RethinkDB is the open-source, scalable database that makes building realtime apps dramatically easier.
icon: logo.png

apps:
 rethinkdb:
   command: bin/launch
   daemon: simple
   uses: [listener]

uses:
  listener:
    type: migration-skill
    caps:
     - network-client
     - network-listener
     - network-service

parts:
  rethinkdb:
    plugin: autotools
    configflags:
      - --allow-fetch
      - --fetch protoc
    source: https://download.rethinkdb.com/dist/rethinkdb-2.2.4.tgz
    build-packages:
      - build-essential
      - protobuf-compiler
      - python
      - libprotobuf-dev
      - libcurl4-openssl-dev
      - libboost-all-dev
      - libncurses5-dev
      - libjemalloc-dev
      - wget
      - m4
  launcher:
    plugin: copy
    files:
      launch.sh: bin/launch
      default.conf: config/default.conf
